// <auto-generated />
using System;
using Gift4U.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gift4U.BlazorApp.Migrations
{
    [DbContext(typeof(GiftDBContext))]
    partial class GiftDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Gift4U.Domain.Models.Gift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gifts");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.GivenGift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("GiftId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GiverId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GiftId");

                    b.HasIndex("GiverId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("GivenGifts");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GivenInRequestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestStateId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Requested")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Responded")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GivenInRequestId");

                    b.HasIndex("RequestStateId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.RequestState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RequestStates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24429bf0-dd4a-486b-aee8-a37ae1e03921"),
                            Name = "Pending"
                        },
                        new
                        {
                            Id = new Guid("22da2c49-a821-4b39-b9cd-b9aff8a6e000"),
                            Name = "RequestApproved"
                        },
                        new
                        {
                            Id = new Guid("e4d0782d-ff97-4783-8ce9-a262d9a7fe54"),
                            Name = "RequestDenied"
                        },
                        new
                        {
                            Id = new Guid("fff72d03-937d-4574-9e3a-6a183ac2cb5f"),
                            Name = "RequestStarted"
                        },
                        new
                        {
                            Id = new Guid("37399d93-2eb8-45d6-8778-717738c101d3"),
                            Name = "Completed"
                        });
                });

            modelBuilder.Entity("Gift4U.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.GivenGift", b =>
                {
                    b.HasOne("Gift4U.Domain.Models.Gift", "Gift")
                        .WithMany("GivenGifts")
                        .HasForeignKey("GiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gift4U.Domain.Models.User", "Giver")
                        .WithMany("GivenGifts")
                        .HasForeignKey("GiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gift4U.Domain.Models.User", "Receiver")
                        .WithMany("ReceivedGifts")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gift");

                    b.Navigation("Giver");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.Request", b =>
                {
                    b.HasOne("Gift4U.Domain.Models.GivenGift", "GivenInRequest")
                        .WithMany("Requests")
                        .HasForeignKey("GivenInRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gift4U.Domain.Models.RequestState", "RequestState")
                        .WithMany("Requests")
                        .HasForeignKey("RequestStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GivenInRequest");

                    b.Navigation("RequestState");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.Gift", b =>
                {
                    b.Navigation("GivenGifts");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.GivenGift", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.RequestState", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Gift4U.Domain.Models.User", b =>
                {
                    b.Navigation("GivenGifts");

                    b.Navigation("ReceivedGifts");
                });
#pragma warning restore 612, 618
        }
    }
}
